### PR TITLE
Add RubyConfLT'15

### PR DESCRIPTION
**Pull request by vidmantas**

### CODE REVIEW

**Comment by jonallured** [comment]
Hi @vidmantas, sorry for the delay on getting this PR merged in. One question: what's the official name of the event? I've seen both "RubyConfLT" and "RubyConf Lithuania". The site style is to not use abbreviations, so I want to make sure I get it right.

Thanks!
Jon

**Comment by vidmantas** [comment]
No worries @jonallured! 

Official name is "RubyConfLT". The event logo, twitter, facebook - everything uses that. The only one "Lithuanian Ruby Conference" is stated as an explanation for the newbies so they actually get it right 100% what it is all about.

**Comment by jonallured** [comment]
Cool, just pulled in your PR and deployed the site - thanks!!
Jon

**Comment by vidmantas** [comment]
Thanks a lot John!

**Pull request closed without merging**
