### PR TITLE
added reg phase and cfp phase to deccanrubyconf

### PR DESCRIPTION
**Pull request by rishijain**

### CODE REVIEW

**Comment by rishijain** [comment]
cc @prathamesh-sonpatki

**Comment by prathamesh-sonpatki** [comment]
Thanks Rishi :smile:

**Comment by jonallured** [comment]
Thanks for the PR, but @robertjlooby beat you to it with #94. :smile:

**Comment by rishijain** [comment]
haha ... its a win-win :heart:

**Pull request closed without merging**
