### PR TITLE
Update RubyConf Colombia 2015

### PR DESCRIPTION
**Pull request by sebasoga**
* Announce CFP
* Announce tickets sale

### CODE REVIEW

**Comment by guilleiguaran** [comment]
:+1:

**Comment by orendon** [comment]
:+1:  :shipit:

**Comment by robertomiranda** [comment]
:+1:

**Comment by jonallured** [comment]
Hey, sorry to nitpick and that it took so long to get back to you, but would you mind amending your commit message. You need a newline between the first line and the others.

Thanks! :heart: :heart: :heart:

**Comment by sebasoga** [comment]
@jonallured done

**Comment by jonallured** [comment]
Thanks dood!!

**Pull request merged**
