### PR TITLE
Add GORUCO 2015 info

### PR DESCRIPTION
**Pull request by jleo3**

### CODE REVIEW

**Comment by jonallured** [comment]
Hi @jleo3 - thanks for the PR! I actually have a question for you: what's the official name of this event?

Site style is to run events with their official names only, but I checked and last year I ran it as "GoRuCo", so I think that was wrong. Is it correct that this event's name is "Gotham Ruby Conference" and it's just referred to as "GoRuCo"?

Sorry, just trying to maintain some sort of consistency here. :)

Thanks!
Jon

**Comment by jleo3** [comment]
Hi, @jonallured. The official name of this event is Gotham Ruby Conference. Yes, it is commonly referred to as "GORUCO" (with varying capitalization). I would like to help keep your data consistent. I'll change the title in whatever way you suggest. Shall I remove "(GORUCO)" from the `name` attribute?

Thanks for hosting this site!

**Comment by jonallured** [comment]
Cool, then let's use the official name. You make the change to your PR and then I'll add a commit on top of it that fixes last year's event.

Thanks!!
Jon

**Comment by jleo3** [comment]
OK, I updated the commit.

**Comment by jonallured** [comment]
Ok, I finally had a chance to pull this in and deploy the site - thanks for being patient! :D

**Comment by jleo3** [comment]
Thanks for merging, @jonallured. One note: rubyconferences.org now says "CFP open in 22 days," which is incorrect. The CFP is open now. It will close in 22 days.

selection_008

**Comment by jonallured** [comment]
Oops - thanks, I had that wrong for all the CFPs! Fixed and redeployed the site! :D

**Comment by jleo3** [comment]
Thanks, @jonallured! We really appreciate being added to the site!

**Pull request closed without merging**
