### PR TITLE
Add jrubyconf and eurucamp

### PR DESCRIPTION
**Pull request by PragTob**
:)

### CODE REVIEW

**Comment by bascht** [comment]
:shipit:

**Comment by pxlpnk** [comment]
:+1:

**Comment by pxlpnk** [comment]
quokka1

**Comment by jonallured** [comment]
Hi @PragTob, thanks for the PR - just a quick clarification: are these events in Potsdam or Berlin? For instance, last year I ran eurucamp like this:

```yml
- name: eurucamp
  location: Potsdam, Germany
  dates: "August 1-3, 2014"
  url: http://2014.eurucamp.org
  twitter: eurucamp
```

Your PR lists eurucamp like this:

```yml
- name: eurucamp
  location: Berlin-Brandenburg, Germany
  dates: "July 31-August 2, 2015"
  url: http://eurucamp.org
  twitter: eurucamp
```

But then the announcement post mentions that the event is actually in Potsdam, so I'm confused. Can you help? :D

**Comment by PragTob** [comment]
@jonallured hi, yeah sure I can :) 

It's Potsdam, when I added it our website still said "Berlin-Brandenburg" and I figured having Berlin is nice because no one knows Potsam.

Changing it to Potsdam would be the correct thing I guess. I can do it this evening/tomorrow or you can do it if you want to.

Thanks :)

**Comment by jonallured** [comment]
Cool, thanks for the clarification - I've just deployed the site!

**Comment by PragTob** [comment]
Thanks a lot :+1:

**Pull request merged**
